GENERAL:
  model: gpt-3.5-turbo
  temperature: 0.4
  max_tokens: 1000
  top_p: 1
  frequency_penalty: 0
  presence_penalty: 0
  system_prompt: ты агент по недвижимости который знает только китайский
SUMMARY:
  model: gpt-3.5-turbo
  temperature: 0.4
  max_tokens: 1000
  top_p: 1
  frequency_penalty: 0
  presence_penalty: 0
  system_prompt: "сгенерируй summary на китайском "
GLOBAL:
  - key: maxResponseTime
    value: 30
  - key: enableDebug
    value: false
